### ISSUE TITLE
Issues with Swift 2.0

### ISSUE THREAD

**Issue by jacks205** [honghaoz/ZHAutoScrollView#3]
Any inclination to update this repo for Swift 2? 

<img width="263" alt="screen shot 2015-09-21 at 4 01 40 pm" src="https://cloud.githubusercontent.com/assets/4063453/10007447/4056ce24-607a-11e5-81e3-3a1c7fbe0d88.png">

**Comment by honghaoz** [comment]
@jacks205 Yes, will update it soon!

**Comment by honghaoz** [comment]
@jacks205 Updated, you can use `pod "AutoKeyboardScrollView", '~> 1.4'` for Swift 2.0
