### ISSUE TITLE
I get the warning: adding view on AutoKeyboardScrollView detected, you should add view on .contentView

### ISSUE THREAD

**Issue by EndBird** [honghaoz/ZHAutoScrollView#7]
**even when im not adding anything in scrollview directly.**  

Heres my code:

 contentView.removeFromSuperview()
        let AutoScrollView = AutoKeyboardScrollView()
         AutoScrollView.layer.frame = CGRect(x: 0, y: 80, width: 375, height: 667)
     
                 AutoScrollView.contentView.addSubview(contentView)
        self.view.addSubview(AutoScrollView)

**Comment by honghaoz** [comment]
Hey @EndBird Thanks for reporting! I've just fixed this bug. You can reinstall this pod, the latest version is `1.5.2`
